URL_SERVICE = "https://78f896d0-4c65-4e26-8de3-45e5363df6c4.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
